name: laptopharbor
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.8
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.0.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.0
  provider: ^6.1.2
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - https://www.shakebugs.com/wp-content/uploads/2022/04/6-tips-onboarding-tehnical-employees.png
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
